# -*- coding: utf-8 -*-
"""car_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q2gH5tM86qE_CcjVnpgDIRlXe5Ah8FeH
"""

!pip install ultralytics

from ultralytics import YOLO

# Load a pre-trained YOLOv8 model
model = YOLO('yolov8n.pt')  # You can choose different models like yolov8s, yolov8m, etc.

# Train the model
results = model.train(
    data='/content/drive/MyDrive/data_traffic.yaml',  # Path to your corrected data configuration file
    epochs=100,  # Number of training epochs
    imgsz=640,  # Image size
    batch=16,  # Batch size
    name='traffic_perception_model',  # Name of the model
)

# After training, evaluate the model on the validation set
metrics = model.val()  # This will evaluate the model and return metrics

# Print accuracy and other metrics
print(f"Precision: {metrics.box.map}")  # mAP (mean Average Precision)
print(f"Recall: {metrics.box.map50}")  # mAP@0.5
print(f"Confusion Matrix: {metrics.confusion_matrix}")  # Confusion matrix

# Export the model to ONNX format (optional)
model.export(format='onnx')

model.val()

model.save('/content/drive/MyDrive/traffic_perception_model.pt')

from ultralytics import YOLO

# Load the saved model
model = YOLO('/content/drive/MyDrive/traffic_perception_model.pt')

# Perform inference on a test image
results = model.predict(source='/content/car1.jpeg', save=True)  # Save the results

# Display the results
for result in results:
    result.show()  # Show the image with predictions

from ultralytics import YOLO

# Load the saved model
model = YOLO('/content/drive/MyDrive/traffic_perception_model.pt')

# Perform inference on a test image
results = model.predict(source='/content/car2.jpeg', save=True)  # Save the results

# Display the results
for result in results:
    result.show()  # Show the image with predictions

from ultralytics import YOLO

# Load the saved model
model = YOLO('/content/drive/MyDrive/traffic_perception_model.pt')

# Perform inference on a test image
results = model.predict(source='/content/car3.jpeg', save=True)  # Save the results

# Display the results
for result in results:
    result.show()  # Show the image with predictions

from ultralytics import YOLO

# Load the saved model
model = YOLO('/content/drive/MyDrive/traffic_perception_model.pt')

# Perform inference on a test image
results = model.predict(source='/content/car4.jpeg', save=True)  # Save the results

# Display the results
for result in results:
    result.show()  # Show the image with predictions

from ultralytics import YOLO

# Load the saved model
model = YOLO('/content/drive/MyDrive/traffic_perception_model.pt')

# Perform inference on a test image
results = model.predict(source='/content/car5.jpeg', save=True)  # Save the results

# Display the results
for result in results:
    result.show()  # Show the image with predictions











